# This file was generated by GoReleaser. DO NOT EDIT.
cask "testcli" do
  name "testcli"
  desc "Test CLI"
  homepage "https://github.com/btschwartz12/testcli"
  version "0.0.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "testy"
  bash_completion "completions/testy.bash"
  zsh_completion "completions/_testy"

  on_macos do
    on_intel do
      url "https://github.com/btschwartz12/testcli/releases/download/v#{version}/testcli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/btschwartz12/testcli/"
      sha256 "d7d41ebaab950eca18c273328b84c6b9142dd35091676e2102a7a513b1496fea"
    end
    on_arm do
      url "https://github.com/btschwartz12/testcli/releases/download/v#{version}/testcli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/btschwartz12/testcli/"
      sha256 "18fad01f5c7b912d135586f500aebacaff1eb5e7392cd9f11fcd14d43fbb10c7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/btschwartz12/testcli/releases/download/v#{version}/testcli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/btschwartz12/testcli/"
      sha256 "0c97b2b180db382d384623a6dd1d68702398ee44e96c4a3b41d9741ba5d5a553"
    end
    on_arm do
      url "https://github.com/btschwartz12/testcli/releases/download/v#{version}/testcli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/btschwartz12/testcli/"
      sha256 "2587037c8c0dad4e19b6320c46f7cbb1b0306513cc62aa52170febb734eafeb0"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/testy"]
    end
  end

  caveats do
    "NOTE: the install executable is 'testy', not 'testcli'. For more info, visit https://github.com/btschwartz12/testcli"
  end

  # No zap stanza required
end
