# This file was generated by GoReleaser. DO NOT EDIT.
cask "testcli" do
  name "testcli"
  desc ""
  homepage ""
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "testy"

  on_macos do
    on_intel do
      url "https://github.com/btschwartz12/testcli/releases/download/v#{version}/testy_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/btschwartz12/testcli/"
      sha256 "649229737ca337a510a5ea2d66dd505489aa00aaf57c3ede568a4819faced8cf"
    end
    on_arm do
      url "https://github.com/btschwartz12/testcli/releases/download/v#{version}/testy_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/btschwartz12/testcli/"
      sha256 "6523dffa49934ad07d8b6be9136db6e2358abf239500854135a01c75efb0aaa4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/btschwartz12/testcli/releases/download/v#{version}/testy_#{version}_linux_amd64.tar.gz",
        verified: "github.com/btschwartz12/testcli/"
      sha256 "93f8c234533966d3d34a00d8c15c300bc3f0bb605205dd423a56851bfa9d3d1f"
    end
    on_arm do
      url "https://github.com/btschwartz12/testcli/releases/download/v#{version}/testy_#{version}_linux_arm64.tar.gz",
        verified: "github.com/btschwartz12/testcli/"
      sha256 "00a6a8eb73c71415689b6134142e09bccec2166fc1b940fe2e0adc2f7f072cc6"
    end
  end

  # No zap stanza required
end
